repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/
      - id: end-of-file-fixer
        exclude: LICENSE
      # - id: check-added-large-files
      #   args: ["--max-kb=500"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --offset, '2', --sequence, '4', --implicit_start]
        files: .pre-commit-config.yaml|\.github/workflows/.*\.yml$

  # - repo: https://github.com/python-jsonschema/check-jsonschema
  #   rev: 0.31.1
  #   hooks:
  #     - id: check-github-workflows
